### ISSUE TITLE
Custom Template for dropdown( mentions list)

### ISSUE THREAD

**Issue by shivmourya98** [nth-cloud/ng-mentions#1]
Hi All,

I would like to raise a new feature, Can we add a custom template for dropdown.
like in dropdown it will show "Name + Type" but in the value section it will show only Name or @Name.

So in this case we can add images/ user type/ email id in the dropdown and in value section it will show name only.

**Comment by trickeyone** [comment]
@shivmourya98 Actually, this was already included. I've added a new section to the demo examples to show how to use this functionality.
