### ISSUE TITLE
[feature] trigger by pressing a button

### ISSUE THREAD

**Issue by jaymehtasa** [nth-cloud/ng-mentions#15]
Can you suggest a workaround to trigger the mention list by pressing a button? example use case shown in following image, clicking on "@" button it should trigger the mention list.

![image](https://user-images.githubusercontent.com/8104992/96258079-1afc6300-0fd9-11eb-96b8-6fdc20c861e0.png)

**Comment by trickeyone** [comment]
@jaymehtasa Sorry I missed this. I'm not really sure, tbh. Is there a reason you wouldn't use the default triggering setup? If you can give me a use-case, it'd be easier to help.

**Comment by jaymehtasa** [comment]
@trickeyone Sorry for late reply.

that is the expected UX, many apps like Trello allowed click on "@" button and also auto triggers by typing "@".

Let me know if possible for you to help.

**Comment by jaymehtasa** [comment]
@trickeyone Please find attached Video of Trello, it works when we typr "@" or click on "@" button both, I ned to achieve same UX.

https://user-images.githubusercontent.com/8104992/110584677-997abc80-8195-11eb-85a6-6d7be28cd06a.mov

**Comment by jaymehtasa** [comment]
@trickeyone also github is ideal example, see attached Video.

https://user-images.githubusercontent.com/8104992/110584834-dd6dc180-8195-11eb-872f-f681f1310dbf.mov

**Comment by jaymehtasa** [comment]
@trickeyone sorry for the follow-up, but any help you can offer here?

**Comment by trickeyone** [comment]
@jaymehtasa Sorry, I've been tied up with work and haven't had a chance to look at this again. Form the Trello example, that looks more like a dropdown list that pops the selected item into the textarea. It looks to me like they utilize two different components to achieve that affect. For Github, it's a simple text-insertion like most typeahead components just without the text formatting that my component does. it just injects the text (i.e. `@jaymehtasa`) into wherever the cursor currently is in a plain textarea.

This formatting is the main sticking point. I can look at adding an externally callable method to trigger the popup/search initialization. This would essentially do the same as pressing the trigger key.

I'm still under a heavy workload at work, so I can't give you an ETA when this will be done.

**Comment by trickeyone** [comment]
closed with 285c3c6

**Comment by trickeyone** [comment]
@jaymehtasa I've added functionality that should cover the use-case you had. Sorry it took so horribly long. Life and work took precedence. See https://nth-cloud.github.io/ng-mentions/#/docs/mentions/examples > Basic example for usage.
