### ISSUE TITLE
Mentions offset due to "non-breakable-spaces" at each line.

### ISSUE THREAD

**Issue by Jagan-P** [nth-cloud/ng-mentions#19]
### Bug description:
When a line occupies all cols of a textarea (when the line is full), all the `mentions` following that line are all offset by one line. This is because "&amp;nbsp;" is added to end of each line and since the current line occupies complete width (all cols) the "&amp;nbsp;" is pushed down.

![image](https://user-images.githubusercontent.com/31800888/145796972-8ce81316-68d1-4603-b2e7-6ea336c343bd.png)

I have fixed this. Will raise a PR.

And thanks for this plugin! :)

### Link to minimally-working plunker that reproduces the issue:
https://stackblitz.com/edit/angular-ivy-xhtejl?file=src%2Fapp%2Fapp.component.ts

### Version of Angular and ng-mentions:

Angular: v12

ng-mentions: v7.0.2

**Comment by Jagan-P** [comment]
#20 created PR for this.

**Comment by trickeyone** [comment]
Closed with #20
