### ISSUE TITLE
Spacing between users/selectors, users are coming one after the other without any gap

### ISSUE THREAD

**Issue by RakeshGowdaM** [nth-cloud/ng-mentions#2]
Hi I have imported this feature in my angular7 app. It's working fine but between the users I'm not able to give space. 

Once I choose @rakesh and next time when I choose the second one as @rajesh, it's coming like rakeshrajesh

There is no space between those two users.

**Comment by trickeyone** [comment]
Hi @RakeshGowdaM. If a space is needed, then the user will need to add a space after the item has been selected. This is by design
