### ISSUE TITLE
Feature to allow "Mention" value to contain spaces

### ISSUE THREAD

**Issue by Jagan-P** [nth-cloud/ng-mentions#34]
### Feature description:
Can we please have a feature to allow spaces in "Mention" values which is not possible right now.

![image](https://user-images.githubusercontent.com/31800888/158818209-33efdeba-26fd-4d4b-b5b4-bc12dc3fc2da.png)

### Version of Angular and ng-mentions:

Angular: NA

ng-mentions: NA

**Comment by trickeyone** [comment]
This is an actual limitation that I had actually spent a lot of time trying to overcome. Unfortunately, if you're wanting simple strings as the mentions (with no special formatting), then this is not possible. You're welcome to try and come up with a workable solution, but I don't currently have the bandwidth to try and find a 100% solution at this time.

**Comment by Jagan-P** [comment]
Oh okay. How do we achieve it with "special formatting"? Could you please help me with suitable example? I just want the mentions to be searchable with spaces.

**Comment by trickeyone** [comment]
@Jagan-P If you look at any of the other examples, you'll see that one of the searchable mentions has a space in the name. The example that says that spaces can't be included is for mentions that aren't formatted. This simply refers to the `markup` that is passed to the component, this default value is `@[__display__](__type__:__id__)`. For the string example you referred to, the `markup` is set to only be `@__display__` which can only search for, format, and display the simple string value for the mention. If you are wanting to have more complex mentions (i.e. spaces in the mention) then you'll need to use the default behavior with at least something similar to the markup indicated.

You'll notice that the `markup` contains placeholders for the values listed for the mentions (i.e. `id`, `display`, and `type`). The component uses the markup indicated to know how for format the mention object and display it.

**Comment by Jagan-P** [comment]
Oh okay. I think I wrongly communicated my need.

In the first example here (https://nth-cloud.github.io/ng-mentions/#/docs/mentions/examples), there is a mention "Bob Ross" which has a space in it. But as soon as I type "Bob " (add a space), the dropdown closes. Is there a way to continue search

**Comment by Jagan-P** [comment]
Oh okay. I think I wrongly communicated my need.

In the first example here (https://nth-cloud.github.io/ng-mentions/#/docs/mentions/examples), there is a mention "Bob Ross" which has a space in it. But as soon as I type "Bob " (add a space), the dropdown closes. Is there a way to continue the search and filter it even after typing spaces?
