### ISSUE TITLE
Removing console log on the mentionList component and extending the behavior of mentions

### ISSUE THREAD

**Issue by Gray-Simon** [nth-cloud/ng-mentions#41]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please search existing issues (both open and closed) prior to opening any new issue and ensure you follow the
instructions therein.

### Bug description: kindly remove the console log on the mention-list component for data integrity sake. especially for users returning an array of objects .

**1. See below code to streamline your search.**

 onItemClick(event: MouseEvent, activeIndex: number, item: any) {
    event.preventDefault();
    **console.log(item);  // kindly remove the console log.**
    if (item) {
      this.activeIndex = activeIndex;
      this.itemSelected.emit(item);
    }
  }
**2. is it possible we have multiple mention configuration with each configuration having their specific triggerCharacter and mentions object e.t.c**

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://nth-cloud.github.io/ng-mentions/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker.

### Version of Angular and ng-mentions:

Angular:

ng-mentions:

**Comment by trickeyone** [comment]
@Gray-Simon Sorry, it's not currently possible to have multiple trigger characters and would be fairly complicated to change the existing behavior to try to add it. If you want to try and take a crack at it, pull requests are always welcome. I don't currently have the bandwidth to try an tackle it myself right now.

I'll try to get a revision out removing the `console.log`  call in the next few days.
