### ISSUE TITLE
multiple mention triggerChar and mentions configuration

### ISSUE THREAD

**Issue by Gray-Simon** [nth-cloud/ng-mentions#42]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please search existing issues (both open and closed) prior to opening any new issue and ensure you follow the
instructions therein.

### Bug description: is it possible we have multiple mention configuration with each configuration having their specific triggerCharacter and mentions object e.t.c

for example: supporting '#'(hastag) and '@'(mention) on the same directives. then their will be a configuration array on the component file:
{
cols: 3;
rows:12;
dropUp: true,
sear
mentionConfig: [
{
triggerChar: '@',
mentions: any[],
},
{
triggerChar: '#',
mentions: any[]
}
]
}

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://nth-cloud.github.io/ng-mentions/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker.

### Version of Angular and ng-mentions:

Angular:

ng-mentions:

**Comment by trickeyone** [comment]
@Gray-Simon As I said in my response to your other ticket (https://github.com/nth-cloud/ng-mentions/issues/41#issuecomment-1205803234), it's not currently possible and would take a decent rework to make it possible. If you want to take a crack at it, please feel free to submit a pull request. I don't currently have the bandwidth to do so with my regular job workload. If you don't mind waiting for a few months, I could try to have something by the end of the year.
