### ISSUE TITLE
Mentions not working on mobile responsiveness

### ISSUE THREAD

**Issue by Gray-Simon** [nth-cloud/ng-mentions#43]
**Mentions not working on mobile responsivess.**

Hi guys, good job so far!
However, how soon can the issue on mobile responsivess be fix, when i try to minimize my screen to tab view or mobile view, the clicked item is not binding to the text area.

This is a major issue. dont know if it is a styling or functionality issue.

![Screenshot 2022-10-10 092346](https://user-images.githubusercontent.com/37146224/194825148-329323e7-0f8e-4afa-99a5-f5ee11cd9fbe.png)

Kindly help look into this.

Thanks,
Best regards.

**Comment by trickeyone** [comment]
@Gray-Simon Can you please provide more information? Browser, OS? I've tested on mobile devices and haven't had any issues. Were you just resizing a browser window on a computer and not mobile device? Thanks in advance.

**Comment by Gray-Simon** [comment]
@trickeyone  thanks to your swift response. I tested on my mobile device am having same issue. so you can check this [https://nth-cloud.github.io/ng-mentions/#/docs/mentions/examples](mentions demo) on your ,mobile phone, and try to mention a user. it works perfectly web on a desktop view.. but it doesnt work on mobile view or on mobile browser.
I tried using the browser phone compatibilty feature and i use a mobile phone as well. i had same experience all through.

For browser compatibility i tried Chrome, Edge, Firefox, Opera same behavior across all this browsers.
OS: Windows and Mac Operating system.

**Comment by Gray-Simon** [comment]
@trickeyone  any luck on the bug fix?

**Comment by trickeyone** [comment]
@Gray-Simon I maintain this in my spare time, which during this time of year is sparse. Without a test case to reproduce the issue you're seeing, it'll be a while. As I said before, I've tested on mobile devices and it operates as expected. If you can give more information (device, browser, versions), it would help.
