### ISSUE TITLE
[Feature Request] Output formatted Mention value

### ISSUE THREAD

**Issue by AFSAngelo** [nth-cloud/ng-mentions#5]
After a user creates a Mention, it would be nice to be able to output that value to an element outside of a text area.  For example, in the text-area I enter "Hi, @trickeyone thanks for making this awesome Angular component!", I'd like to output that to a regular HTML element, say a simple paragraph (i.e. `<p>{{ model.value }}</p>)`, where then the mention is highlighted similar to how it is in the text area.  An example would be how Slack displays the mention in a list after it's been entered in the text area.  Thanks in advance and great work!

### Version of Angular and ng-mentions:

Angular: 7.0

ng-mentions: 2.0.3

**Comment by trickeyone** [comment]
So, you're looking for a component that would format the content? I actually made something that works with this component for my work project that does that. I can look at adding a new component that does something similar.

**Comment by AFSAngelo** [comment]
@trickeyone exactly, and that sounds great regarding the work project component.  Thanks for the reply and let me know if there's any way I could help and/or just implement separately if you don't want to add it to the core project

**Comment by trickeyone** [comment]
Hi @AFSAngelo, I didn't want you to think I'd forgot about this. Work and person life have been crazy busy. I'll try to get to this sometime in the next month.

**Comment by AFSAngelo** [comment]
No worries at all!  Thank you for the update!

**Comment by trickeyone** [comment]
Just an update, I haven't forgotten about this. I'm working on it and have it mostly done. Just having to revamp the demo site to accommodate multiple components. Should be up this weekend.

**Comment by AFSAngelo** [comment]
Awesome, looking forward to it and hope you had a great weekend!
