### ISSUE TITLE
[Feature Request] Mentions in input and embed editor.

### ISSUE THREAD

**Issue by danbatistar4** [nth-cloud/ng-mentions#7]
I would like to request a feature, to be able to use mentions in inputs and embed editors.

**Comment by trickeyone** [comment]
Sorry for the late reply, @danbatistar4 . Do you mean using another editor? i.e. a markdown or wysiwyg editor? I'd need more info to be able to help you.

**Comment by danbatistar4** [comment]
I would like to use in a markdown like ngxeditor.

**Comment by trickeyone** [comment]
Then it's probably not going to work. I haven't really experimented with using multiple modifiers on a single input/binding. Have you tried it already? If so, what was the experience. Providing an example via Stackblitz would be helpful.
